### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by Yanren1225** [jmeubank/tdm-gcc-src#2] opened 2020-07-06 06:51 UTC
cd "c:\Users\nihao\dock_menu\code\SJJG\Structure\" ; if ($?) { gcc *.c -o structure.exe } ; if ($?) { .\structure.exe }
gcc.exe: error: *.c: Invalid argument
gcc.exe: fatal error: no input files
compilation terminated.

**Comment by jmeubank** [comment] 2021-05-21 01:21
Duplicate of https://github.com/jmeubank/tdm-gcc/issues/12 .

**Closed as completed by jmeubank** 2021-05-21 01:21 UTC
Labels: duplicate
